name: Build and Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Failbreak
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos sdk (Team Failure Procursus patched)
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Team-Failure/theos/refs/heads/master/bin/install-sdk latest)"

      - name: Install Theos (Team Failure Procursus patched)
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Team-Failure/theos/refs/heads/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Make Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Failbreak.app
          path: ./packages/
